#### Understanding my data

In [4]:
import pandas as pd
df= pd.read_csv('bmw.csv')

##### 1. How big is the data?

In [5]:
df.shape

(10781, 9)

##### 2. How does the data look like?

In [6]:
df.sample(5)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
7404,3 Series,2007,3495,Manual,130000,Petrol,200,44.8,2.0
1467,2 Series,2019,21773,Automatic,123,Diesel,145,49.6,2.0
7938,5 Series,2013,10999,Automatic,89693,Diesel,125,57.6,2.0
4900,3 Series,2019,27990,Manual,4465,Diesel,145,54.3,2.0
2853,7 Series,2014,13600,Automatic,78094,Diesel,160,50.4,3.0

##### 3. What is trhe datatype of cols?

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10781 entries, 0 to 10780
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         10781 non-null  str
 1   year          10781 non-null  int64
 2   price         10781 non-null  int64
 3   transmission  10781 non-null  str
 4   mileage       10781 non-null  int64
 5   fuelType      10781 non-null  str
 6   tax           10781 non-null  int64
 7   mpg           10781 non-null  float64
 8   engineSize    10781 non-null  float64
dtypes: float64(2), int64(4), str(3)
memory usage: 986.8 KB

##### 4. Are there any missing values?

In [8]:
df.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

##### 5. How does the data look mathematically?

In [9]:
df.describe()

,year,price,mileage,tax,mpg,engineSize
count,10781.000000,10781.000000,10781.000000,10781.000000,10781.000000,10781.000000
mean,2017.078935,22733.408867,25496.986550,131.702068,56.399035,2.167767
std,2.349038,11415.528189,25143.192559,61.510755,31.336958,0.552054
min,1996.000000,1200.000000,1.000000,0.000000,5.500000,0.000000
25%,2016.000000,14950.000000,5529.000000,135.000000,45.600000,2.000000
50%,2017.000000,20462.000000,18347.000000,145.000000,53.300000,2.000000
75%,2019.000000,27940.000000,38206.000000,145.000000,62.800000,2.000000
max,2020.000000,123456.000000,214000.000000,580.000000,470.800000,6.600000

##### 6. Are there any duplicate values?

In [10]:
df.duplicated().sum()

np.int64(117)

##### 7. How is the correlation between cols?

In [12]:
df.corr(numeric_only= True)

                year     price   mileage       tax       mpg  engineSize
year        1.000000  0.623756 -0.774382  0.025200 -0.071762   -0.026337
price       0.623756  1.000000 -0.605397  0.263484 -0.204882    0.460196
mileage    -0.774382 -0.605397  1.000000 -0.170747  0.118609   -0.002540
tax         0.025200  0.263484 -0.170747  1.000000 -0.351798    0.429616
mpg        -0.071762 -0.204882  0.118609 -0.351798  1.000000   -0.399844
engineSize -0.026337  0.460196 -0.002540  0.429616 -0.399844    1.000000

In [14]:
df.corr(numeric_only=True)['price']

year          0.623756
price         1.000000
mileage      -0.605397
tax           0.263484
mpg          -0.204882
engineSize    0.460196
Name: price, dtype: float64