In [2]:
import numpy as np
import pandas as pd

In [3]:
df= pd.read_csv("titanic.csv")

In [4]:
df.sample(5)

    Cabin  Ticket number  Survived
19    NaN    2649      4         1
857   E17  113055      A         1
255   NaN    2650      3         1
223   NaN  349234      A         0
584   NaN    3411      A         0

In [5]:
df['number'].unique()

<ArrowStringArray>
['5', '3', '6', 'A', '2', '1', '4']
Length: 7, dtype: str

# Extracting Numerical Part

In [6]:
df['number_numerical']= pd.to_numeric(df["number"], errors= 'coerce', downcast='integer')
# It converts the number column into numeric form and stores it in a new column number_numerical.
# errors='coerce' If a value cannot be converted, it becomes NaN instead of throwing an error.

# Extracting Categorical Part

In [7]:
df['number_categorical']= df['number'].where(df['number_numerical'].isna())

In [8]:
df.sample(4)

    Cabin    Ticket number  Survived  number_numerical number_categorical
295   NaN  PC 17612      A         0               NaN                  A
32    NaN    335677      6         1               6.0                NaN
245   C78     19928      5         0               5.0                NaN
266   NaN   3101295      6         0               6.0                NaN

In [9]:
df['Cabin'].unique()

<ArrowStringArray>
[          nan,         'C85',        'C123',         'E46',          'G6',
        'C103',         'D56',          'A6', 'C23 C25 C27',         'B78',
 ...
        'B102',         'B69',         'E49',         'C47',         'D28',
         'E17',         'A24',         'C50',         'B42',        'C148']
Length: 148, dtype: str

In [10]:
df['Ticket'].unique()

<ArrowStringArray>
[       'A/5 21171',         'PC 17599', 'STON/O2. 3101282',
           '113803',           '373450',           '330877',
            '17463',           '349909',           '347742',
           '237736',
 ...
           '349212',           '349217',           '349257',
             '7552', 'C.A./SOTON 34068',  'SOTON/OQ 392076',
           '211536',           '112053',           '111369',
           '370376']
Length: 681, dtype: str

In [11]:
df['cabin_num']= df['Cabin'].str.extract('(\d+)')  # extracts numerical part.
df['cabin_cat']= df['Cabin'].str[0] # extract first letter as cabin name has first letter in categorical form.

In [12]:
df

,Cabin,Ticket,number,Survived,number_numerical,number_categorical,cabin_num,cabin_cat
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN
1,C85,PC 17599,3,1,3.0,NaN,85,C
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN
3,C123,113803,3,1,3.0,NaN,123,C
4,NaN,373450,A,0,NaN,A,NaN,NaN
...,...,...,...,...,...,...,...,...
886,NaN,211536,3,0,3.0,NaN,NaN,NaN
887,B42,112053,3,1,3.0,NaN,42,B
888,NaN,W./C. 6607,1,0,1.0,NaN,NaN,NaN
889,C148,111369,2,1,2.0,NaN,148,C
890,NaN,370376,3,0,3.0,NaN,NaN,NaN

In [17]:
df[['ticket_cat','ticket_num']] = df['Ticket'].str.extract(r'([A-Za-z0-9\/\.\-]+)\s*(\d+)')

In [18]:
df

,Cabin,Ticket,number,Survived,number_numerical,number_categorical,cabin_num,cabin_cat,ticket_cat,ticket_num
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN,A/5,21171
1,C85,PC 17599,3,1,3.0,NaN,85,C,PC,17599
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN,STON/O2.,3101282
3,C123,113803,3,1,3.0,NaN,123,C,11380,3
4,NaN,373450,A,0,NaN,A,NaN,NaN,37345,0
...,...,...,...,...,...,...,...,...,...,...
886,NaN,211536,3,0,3.0,NaN,NaN,NaN,21153,6
887,B42,112053,3,1,3.0,NaN,42,B,11205,3
888,NaN,W./C. 6607,1,0,1.0,NaN,NaN,NaN,W./C.,6607
889,C148,111369,2,1,2.0,NaN,148,C,11136,9
890,NaN,370376,3,0,3.0,NaN,NaN,NaN,37037,6